name: Deploy to Knative

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Kubeconfig
      env:
        KUBECONFIG_DATA: ${{ secrets.KUBECONFIG }}
      run: |
        echo "$KUBECONFIG_DATA" | base64 -d > kubeconfig
        export KUBECONFIG=kubeconfig

    - name: Deploy to Knative
      env:
        IMAGE: ghcr.io/jkcoper/prueba-temp-python:latest
      run: |
        kn service create myservice \
        --image $IMAGE \
        --port 8080 \
        --env TARGET=World || \
        kn service update myservice \
        --image $IMAGE \
        --port 8080 \
        --env TARGET=World
